// Generated by gencpp from file rostestm/envoi.msg
// DO NOT EDIT!


#ifndef ROSTESTM_MESSAGE_ENVOI_H
#define ROSTESTM_MESSAGE_ENVOI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostestm
{
template <class ContainerAllocator>
struct envoi_
{
  typedef envoi_<ContainerAllocator> Type;

  envoi_()
    : num(0)  {
    }
  envoi_(const ContainerAllocator& _alloc)
    : num(0)  {
    }



   typedef int64_t _num_type;
  _num_type num;




  typedef boost::shared_ptr< ::rostestm::envoi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostestm::envoi_<ContainerAllocator> const> ConstPtr;

}; // struct envoi_

typedef ::rostestm::envoi_<std::allocator<void> > envoi;

typedef boost::shared_ptr< ::rostestm::envoi > envoiPtr;
typedef boost::shared_ptr< ::rostestm::envoi const> envoiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostestm::envoi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostestm::envoi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rostestm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rostestm': ['/home/viki/catkin_ws/src/rostestm/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rostestm::envoi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostestm::envoi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostestm::envoi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostestm::envoi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostestm::envoi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostestm::envoi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostestm::envoi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57d3c40ec3ac3754af76a83e6e73127a";
  }

  static const char* value(const ::rostestm::envoi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57d3c40ec3ac3754ULL;
  static const uint64_t static_value2 = 0xaf76a83e6e73127aULL;
};

template<class ContainerAllocator>
struct DataType< ::rostestm::envoi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostestm/envoi";
  }

  static const char* value(const ::rostestm::envoi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostestm::envoi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n\
";
  }

  static const char* value(const ::rostestm::envoi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostestm::envoi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct envoi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostestm::envoi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostestm::envoi_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTESTM_MESSAGE_ENVOI_H
